Petstagram/pets/urls.py
from django.urls import path

from pets.views import list_pets, details_or_comment_pet, like_pet, edit_pet, delete_pet, create_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('detail/<int:pk>/', details_or_comment_pet, name='pet details or comment'),
    path('like/<int:pk>/', like_pet, name='like pet'),
    path('edit/<int:pk>/', edit_pet, name='edit pet'),
    path('delete/<int:pk>/', delete_pet, name='delete pet'),
    path('create/', create_pet, name='create pet'),
]

Petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('petstagram.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('pets/', include('petstagram.pets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram/pets/models.py
from django.db import models

from accounts.models import UserProfile


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    UNKNOWN = 'unknown'
    PET_TYPES = [
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (PARROT, 'Parrot'),
        (UNKNOWN, 'Unknown'),
    ]
    type = models.CharField(max_length=7, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=6, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(
        upload_to='pets',
    )
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

Petstagram/templates/landing_page.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="{% url 'login' %}"
                                                                        class="btn btn-lg btn-secondary">sign
                            in</a></p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <a href="{% url 'signup user' %}" class="btn btn-lg btn-secondary">sign up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Petstagram/templates/pet_create.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Petstagram/templates/pet_delete.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ pet.name }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete pet' pet.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-danger">
                            Confirm
                        </button>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Petstagram/templates/pet_detail.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image.url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u> {{ pet.type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                <h5><u>Age:</u> {{ pet.age }}</h5>
                <h5><u>Owner:</u> <a href="{% url 'user profile' pet.user.user_id %}"> {{ pet.user.user.username }}</a>
                </h5>
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <div>
                {% if can_edit %}
                    <a href="{% url 'edit pet' pet.pk %}" class="btn btn-success">Edit</a>
                {% endif %}
                {% if can_delete %}
                    <a href="{% url 'delete pet' pet.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
            {% if can_like %}
                {% if has_liked %}
                    <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                {% else %}
                    <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                {% endif %}
            {% endif %}
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.all %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <a href="{% url 'user profile' comment.user_id %}">{{ comment.user.user.username }}</a>
                    <h5><em>{{ comment.text }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        {% if can_comment %}
            <div class="box">
                <form method="post" action="{% url 'comment pet' pet.pk %}">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

Petstagram/templates/pet_edit.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Edit pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <img id="img_preview" src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block"/>
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <script>
        function updateImage() {
            var img = document.getElementById('img_preview');
            var url = this.value;
            img.src = url;
        }

        document.getElementById('img_input')
            .addEventListener('input', updateImage);
    </script>
{% endblock %}

Petstagram/templates/pet_list.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class='text-center'>All pet photos</h1>
    <div class="row">
        {% for pet in pets %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ pet.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                        <p class="card-text">{{ pet.description }}</p>
                        <a href="{% url 'pet details' pet.id %}" class="btn btn-primary">See details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}